### ISSUE TITLE
'Type Error: Assignment to constant variable' after updating to node-chartist 1.0.1

### ISSUE THREAD

**Issue by a2raoof** [panosoft/node-chartist#13]
I am getting an error:

UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Assignment to constant variable.

After updating to node-chartist 1.0.1

This happens during the following call

`const bar = generate('line', options, data).then((output) => {
...
}`

I have tried setting the options both using the new Chartist object introduced in this update and without. I tried reverting back to a previous version and it works fine, but I do want to have access to the Chartist options.

**Comment by alexgig** [comment]
Hi @a2raoof,

Please send enough code to reproduce the issue and I can take a look.

Best,
Alex

**Comment by a2raoof** [comment]
Hi @alexgig 

I was able to produce the results with:

`  const options =  {
    width: 500,
    height: 400,
  };

  const data = {

    labels: ['A', 'B', 'C'],

    series: [
      {name: 'A', value:[2, 2.5, 1]},
      {name: 'B', value:[3, 3, 2]},
      {name: 'C', value:[4, 1, 1]}
    ]
  }
  const bar = generate('line', options, data);`

Thanks

**Comment by alexgig** [comment]
Make options a `var` instead of a `const` and it should work.

Best regards,
Alexandre Gigliotti

--

Alexandre Gigliotti

Panoramic Software, Inc <http://www.panosoft.com/>

Software Architect

Office: 1-(877)-558-8526 x712  | alex@panosoft.com


*"**Serving states and counties across the country since 1982..."*

**Comment by alexgig** [comment]
version of node?

**Comment by a2raoof** [comment]
v6.8.0

Do I need to update this to the latest? It was working with this version of node prior to the update to node-chartist v1.0.1

**Comment by alexgig** [comment]
Should be good to go. Tests pass on `node v6.9`

**Comment by a2raoof** [comment]
Great! Works :)

Thanks for the help and quick response (Y)

**Comment by alexgig** [comment]
Excellent. You're welcome and thanks for posting the issue.

Happy charting! :-)

Best,
Alex
