### ISSUE TITLE
Pie chart error: <path> attribute d: Expected number, "MNaN,NaNA245,245,…".

### ISSUE THREAD

**Issue by ramtinsoltani** [panosoft/node-chartist#14]
I'm trying to create a simple pie chart (have successfully created a line chart before) but I get the following errors in the console (Dev Tools):

```
Error: <path> attribute d: Expected number, "MNaN,NaNA245,245,…".
Error: <text> attribute dx: Expected length, "NaN".
Error: <text> attribute dy: Expected length, "NaN".
```

The code I'm running is:

```
const chartist = require('node-chartist');

var options = {

  width: 500,
  height: 500

};

var data = {

  series: [
    [5,7,3]
  ]

};

chartist('pie', options, data)
.then(function(chart) {

  // Save into HTML with Chartist CSS file...

});
```

Is this an actual bug or am I doing something wrong?

**Comment by alexgig** [comment]
Hi @ramtinsoltani,

The series property for pie charts is an array, not an array of arrays.

Best,
Alex

**Comment by ramtinsoltani** [comment]
Thanks, it worked.

**Comment by alexgig** [comment]
You're welcome.

Best regards,
Alexandre Gigliotti
