### ISSUE TITLE
stacked bar chart doesn't render

### ISSUE THREAD

**Issue by thetrav** [panosoft/node-chartist#16]
Use the example from the chartist site: http://gionkunz.github.io/chartist-js/examples.html#stacked-bar

svg is rendered with incorrect heights, looks like single full height bars

**Comment by alexgig** [comment]
Hi Travis,

We can reproduce the issue but don't know what's causing it. At this time we are only supporting simple bar, line, and pie charts. If you would like to look into this further, pull requests are welcome!

Sorry for the inconvenience.

Best regards,
Alex
