### ISSUE TITLE
Possible to use plugins?

### ISSUE THREAD

**Issue by psarin** [panosoft/node-chartist#23]
Is it possible to use plugins? If so, how could I do this. For example, I'd like to use the chartist ctPointLabels plugin (https://gionkunz.github.io/chartist-js/plugins.html). Thanks! Great library, btw!

**Comment by cscalfani** [comment]
Not sure how. The developer who built this left the company. I'd suggest you look at the codebase.

Sorry I cannot be of more help.

**Comment by alexgig** [comment]
Hi @psarin,

This has not been tested but I believe it should work. I suggest giving it a try.

The `options` object supplied to the `generate` function is passed through to the appropriate Chartist rendering function. Thus, including the `plugins` key in that object should work the same as if it was included in the Chartist `options` object.

I hope that helps.

**Comment by psarin** [comment]
The API says to pass in the plugin’s function as part of the options.plugins object. Unfortunately, the plugin needs access to the Chartist instance but this isn’t accessible (or even created) at the level of the calling function. Importing the plugin also requires access to window object, which is also not available to the calling function.

Cage

**Comment by alexgig** [comment]
Hi @psarin 

From the generate documentation:

> options - An object or a function that returns an object of chart options. If a function is used, it will be called with the Chartist object.

Using a function here should give you access to what you need.

**Comment by psarin** [comment]
Thanks, that helps but unfortunately, I’m not clear how or where to import the plugin. If I use require to pull it in, it complains that “window” is not defined.

I could modify the source files to perform the import after window is defined but that seems as if it would break encapsulation of the project.
