### ISSUE TITLE
npm run build failed

### ISSUE THREAD

**Issue by Steve24by7** [panosoft/node-chartist#4]
On Ubuntu
npm version 2.14.4
node version 4.1.1

It claims "FileError" not found, as below, but the files are there and have 777 perms.

root@bsa12:/var/www/html# npm install node-chartist
|
> node-chartist@0.2.6 postinstall /var/www/html/node_modules/node-chartist
> npm run build

> node-chartist@0.2.6 prebuild /var/www/html/node_modules/node-chartist
> rimraf dist/*

> node-chartist@0.2.6 build /var/www/html/node_modules/node-chartist
> lessc lib/main.less dist/main.css && touch node_modules/canvas.js

FileError: '../node_modules/chartist/dist/chartist.min.css' wasn't found. Tried - /var/www/html/node_modules/node-chartist/node_modules/chartist/dist/chartist.min.css,/var/www/html/node_modules/node-chartist/node_modules/chartist/dist/chartist.min.css,../node_modules/chartist/dist/chartist.min.css in /var/www/html/node_modules/node-chartist/lib/main.less on line 1, column 1:
1 @import (less) '../node_modules/chartist/dist/chartist.min.css';
2 

npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! node-chartist@0.2.6 build: `lessc lib/main.less dist/main.css && touch node_modules/canvas.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-chartist@0.2.6 build script 'lessc lib/main.less dist/main.css && touch node_modules/canvas.js'.
npm ERR! This is most likely a problem with the node-chartist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lessc lib/main.less dist/main.css && touch node_modules/canvas.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-chartist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/node_modules/node-chartist/npm-debug.log
npm ERR! Linux 3.19.0-25-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "node-chartist"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE

npm ERR! node-chartist@0.2.6 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-chartist@0.2.6 postinstall script 'npm run build'.
npm ERR! This is most likely a problem with the node-chartist package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-chartist
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/html/npm-debug.log

**Comment by alexgig** [comment]
Hi @Steve24by7,

Thanks for filing this issue. In the next release of node chartist we will be using a CI server to run the build which will resolve this issue.

We'll notify you via this issue once that's complete.

Best regards,
Alex

**Comment by dibyom** [comment]
I am running into the same issue on a Mac. Any timeline on the next release?

**Comment by alexgig** [comment]
Hey Guys,

This issue has been resolved in + node-chartist@0.2.7.

Happy Charting!

Best,
Alex
