### ISSUE TITLE
package.json engines section

### ISSUE THREAD

**Issue by nagylajcsie** [panosoft/node-chartist#8]
Using yarn package manager I found this error:

`error node-chartist@0.2.8: The engine "node" is incompatible with this module. Expected version "^4.0.0".`

which is caused by the engines section of packages.json being too restrictive:

```
"engines": {
    "node": "^4.0.0",
    "npm": "^2.0.0"
  },

```
4.* is rather old version. Please replace it with >= if possible. Thx!

**Comment by alexgig** [comment]
Hello @nagylajcsie,

Fixed in `+ node-chartist@0.2.9`. Thanks for the issue.

Best,
Alex
